#ifndef FRC1810_SPI_CONSTANTS_H
#define FRC1810_SPI_CONSTANTS_H

// Protocol
#define SPI_READ 0x0B
#define SPI_WRITE 0x0A

// Identification
#define REGISTER_DEVICE_ID_0 0x00
#define REGISTER_DEVICE_ID_VALUE_0 0xAD
#define REGISTER_DEVICE_ID_1 0x01
#define REGISTER_DEVICE_ID_VALUE_1 0x1D
#define REGISTER_PART_ID 0x02
#define REGISTER_PART_ID_VALUE 0xF2
#define REGISTER_SILICON_REVISION_ID 0x03
#define REGISTER_SILICON_REVISION_ID_VALUE 1

// Status
#define REGISTER_STATUS 0x0B
#define REGISTER_STATUS_DATA_READY 0b00000001

// FIFO
#define REGISTER_FIFO_CONTROL 0x28
#define REGISTER_FIFO_CONTROL_VALUE 0b00000000

// Data
#define REGISTER_X 0x0E
#define REGISTER_Y 0x10
#define REGISTER_Z 0x12

// Reset
#define REGISTER_RESET 0x1F
#define REGISTER_RESET_VALUE 'R'

// Power
#define REGISTER_POWER_CONTROL 0x2D
#define REGISTER_POWER_CONTROL_VALUE 0b00100010

#endif
