#ifndef FRC1810_SPI_CONSTANTS_H
#define FRC1810_SPI_CONSTANTS_H

// Protocol
#define SPI_READ 0x0B
#define SPI_WRITE 0x0A

// Identification
#define REGISTER_ID 0x00
#define REGISTER_ID_VALUE_0 0xAD
#define REGISTER_ID_VALUE_1 0x1D
#define REGISTER_ID_VALUE_2 0xF2
#define REGISTER_ID_VALUE_3 0x01

// FIFO
#define REGISTER_FIFO_CONTROL 0x28
#define REGISTER_FIFO_CONTROL_VALUE 0b00000000

// Data
#define REGISTER_X 0x0E
#define REGISTER_Y 0x10
#define REGISTER_Z 0x12

// Reset
#define REGISTER_RESET 0x1F
#define REGISTER_RESET_VALUE 'R'

// Power
#define REGISTER_POWER_CONTROL 0x2D
#define REGISTER_POWER_CONTROL_VALUE 0b00100010

#endif
